repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.1" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      # - id: poetry-export
      - id: poetry-install
  - repo: local
    hooks:
      - id: ruff-fix
        name: Run ruff check --fix
        entry: poetry run ruff check --fix --show-fixes
        language: system
        types: [python]
      - id: ruff-format
        name: Run ruff format
        entry: poetry run ruff format --force-exclude
        language: system
        types: [python]
      - id: pytest
        name: Run tests
        entry: poetry run pytest tests
        language: system
        types: [python]
