repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.1" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      # - id: poetry-export
      - id: poetry-install
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.7"
    hooks:
      - id: ruff
      - id: ruff-format
